### ISSUE TITLE
Broken doc link on main page

### ISSUE THREAD

**Issue by MaxWilson** [fabulous-dev/Fabulous.MauiControls#12]
Main page says "For a starter guide see our [Get Started with Fabulous.MauiControls](https://fabulous.dev/maui.controls/get-started)."

But https://fabulous.dev/maui.controls/get-started is a 404.

Impact: my Hello World exploration of Fabulous is temporarily blocked.

**Comment by TimLariviere** [comment]
@MaxWilson Sorry about this. The links are temporary placeholders while we are working on a new website.
In the meantime, you can check the existing documentation at https://docs.fabulous.dev/v2/getting-started/
Docs mentions Xamarin.Forms, but it's very similar for Maui.Controls

**Comment by MaxWilson** [comment]
Thanks, I'll check it out.
