### ISSUE TITLE
Incorrect command in the docs?

### ISSUE THREAD

**Issue by njlr** [fabulous-dev/Fabulous.MauiControls#45]
https://docs.fabulous.dev/maui/get-started#install-the-templates

The command in the docs failed for me

```bash
dotnet new install Fabulous.MauiControls.Templates
```

This worked instead:

```bash
dotnet new --install Fabulous.MauiControls.Templates
```

And this:

```bash
dotnet new list
```

Should be this:

```
dotnet new --list
```

Happy to send a PR!

```bash
$ dotnet --version
6.0.401
```

**Comment by edgarfgp** [comment]
Thanks for raising this. Based on https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-install 
- NET 6 requires the `--install`
- NET 7 + has been simplified to just `install`

Looking at the  NET Multi-platform App UI (.NET MAUI) [Support Policy ](https://dotnet.microsoft.com/en-us/platform/support/policy/maui) `NET 6` is out of support and we want to encourage people to use NET 7 or the upcoming NET8 as MAUI is more stable.

I think we could be more explicit in the README about using NET 7 + to try Fabulous.MauiControls
