### ISSUE TITLE
WebView does not render content

### ISSUE THREAD

**Issue by causa-prima** [fabulous-dev/Fabulous.MauiControls#63]
I can't get the WebView control to render anything, not even hardcoded HTML. I've created a sample project by creating a new project with `dotnet new fabulous-mauicontrols -n WebViewTest` and replaced the `ScrollView` with the following code:
```fsharp
VStack(spacing = 5.) {
    Label("Title")
    Label("Date")
    WebView(html = "<html><body><p>Test Test Test</p></body></html>")
    WebView(url = "http://www.google.com")
    Label("After WebView")
}
```
Debugging the app with the profile "Windows Machine" I can only see the labels, but not the WebView:
![grafik](https://github.com/fabulous-dev/Fabulous.MauiControls/assets/2970704/3cc1bd5c-7af2-4a64-89b2-c5f9f5ed601a)

Here's the solution I used:
[WebViewTest.zip](https://github.com/fabulous-dev/Fabulous.MauiControls/files/14430547/WebViewTest.zip)

**Comment by edgarfgp** [comment]
@causa-prima. Tested this on android, iOS, macCatalyst and works as expected, based on your screenshot Im assuming that you are running this in Windows right ?. I think is not a Fabulous issue might be windows related maybe permissions. Also have you read https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/webview?view=net-maui-8.0&pivots=devices-windows ?

**Comment by causa-prima** [comment]
@edgarfgp : Yes, I'm running on windows (couldn't get the android emulator to work correctly yet). And yes, I've read the documentation you linked to. At the end of the first paragraph you can find the following sentence:
> By default, .NET MAUI projects include the platform permissions required for a [WebView](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.webview) to display a remote web page.

Thus, I'd assume that it's not a permission-related problem. I'll still dig around to see if I can find any related info that will help (any hints are appreciated).

Btw: Your android screenshot seems to be missing the `Title` and `Date` labels, and both display the second `Test` as bold in the hard coded HTML example. I guess you adjusted the code, right?

**Comment by causa-prima** [comment]
Well, this is awkward. In my example, you just need to set the height of the `WebView` to some fixed value, e.g. `WebView(html = "<html><body><p>Test Test Test</p></body></html>").height(50.)`. I guess the behavior of `VStack` differ between platforms in the way the sizes are calculated. With your findings, I also gave the android emulator a try, and with my original example the layout in my actual app was switching between two different states, but with a fixed size everything is fine.

So my lesson learned for today: If you can't see something that should be there, try explicitly changing the size to something that must be visible.

Anyways, thanks for the quick support that lead me to the right solution!

**Comment by edgarfgp** [comment]
No worries. Happy that you figure out this :). Feel free to raise more issues if necesary
