### ISSUE TITLE
Setting a WebViewer's MixedContentMode to AlwaysAllow on Android does not work

### ISSUE THREAD

**Issue by causa-prima** [fabulous-dev/Fabulous.MauiControls#65]
I have a WebViewer, with which I want to display HTML from RSS feeds. This generally works, but for one of the feeds I'm testing with I get some HTML that contains an image with src set to some address using the HTTP protocol (not HTTPS). I suspect that the initial "load" probably happens in HTTPS (even though I directly provide the HTML, not just some URL), and the img with the HTTP src won't get loaded because of that. I found some article about this (https://learn.microsoft.com/en-us/dotnet/maui/android/platform-specifics/webview-mixed-content?view=net-maui-8.0) and think I applied it correctly, but still, the image is not loaded. What am I doing wrong?

I've created a sample project to demonstrate the problem: [WebViewMixedContentTest.zip](https://github.com/fabulous-dev/Fabulous.MauiControls/files/14905478/WebViewMixedContentTest.zip)

Here's the relevant sample code that demonstrates the problem:
```FSharp
    let html = """<img src="http://www.qwantz.com/comics/comic2-4374.png"
                      title='hesternal means "of or pertaining to yesterday" and long-time dino comics readers already know and love and use "nudiustertian", meaning "the day before yesterday".  you can tell a long-time dino comics readers by how hodie they sound AND ARE!!'
                      data-sanitized-class="comic">
                  <br>
                  <img src="https://www.qwantz.com/comics/comic2-4374.png"
                      title='hesternal means "of or pertaining to yesterday" and long-time dino comics readers already know and love and use "nudiustertian", meaning "the day before yesterday".  you can tell a long-time dino comics readers by how hodie they sound AND ARE!!'
                      data-sanitized-class="comic">"""
    
    let view model =
        Application(
            ContentPage(
                let webViewRef = ViewRef<Microsoft.Maui.Controls.WebView>()
                let webViewControl = WebView(html = html)
                                        .reference(webViewRef)
                                        .gridRow (1)
                match webViewRef.TryValue with
                | None -> ()
                | Some webView -> webView.On<Microsoft.Maui.Controls.PlatformConfiguration.Android>()
                                            .SetMixedContentMode(MixedContentHandling.AlwaysAllow) |> ignore
                
                webViewControl
            )
        )
```

This produces the following output on my emulated android device as well as my android phone, where the first image is not displayed, while the second one is:

![grafik](https://github.com/fabulous-dev/Fabulous.MauiControls/assets/2970704/15d5f563-e2cd-4728-94e9-f5aa45b83ee6)

**Comment by dminta** [comment]
Hello @causa-prima, you should add [android:usesCleartextTraffic](https://developer.android.com/guide/topics/manifest/application-element#usesCleartextTraffic) to your `AndroidManifest.xml`; here is the modified file:

~~~
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
	<application android:allowBackup="true" android:icon="@mipmap/appicon" android:roundIcon="@mipmap/appicon_round" android:supportsRtl="true" android:usesCleartextTraffic="true"></application>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
</manifest>
~~~

**Comment by causa-prima** [comment]
Thanks, this seems to solve the issue!
