### ISSUE TITLE
Template and examples do not define project folders

### ISSUE THREAD

**Issue by ners** [fabulous-dev/Fabulous.MauiControls#67]
Following [the getting started guide](https://docs.fabulous.dev/maui/get-started) and running `dotnet new fabulous-mauicontrols -n GetStartedApp` produces a project with the following contents in the fsproj:

```xml
  <ItemGroup Condition="$(TargetPlatformIdentifier) == 'windows'">
    <Manifest Include="$(WindowsProjectFolder)app.manifest" />
    <AppxManifest Include="$(WindowsProjectFolder)Package.appxmanifest" />
    <Compile Include="$(WindowsProjectFolder)App.fs" />
    <Compile Include="$(WindowsProjectFolder)Main.fs" />

    <PackageReference Include="FSharp.Maui.WinUICompat" />
  </ItemGroup>
```

These files exist in the subdirectory `Platforms/Windows`, but the variable `WindowsProjectFolder` is never set.

When this project is opened in JetBrains Rider, it shows these files as missing in the root of the project.

What is the correct / expected way for the variable `WindowsProjectFolder` to be set?

**Comment by TimLariviere** [comment]
`WindowsProjectFolder` is a variable defined by Maui and should be automatically imported.

If not, it usually means you are missing Maui dependencies on your machine.

Could you try running `dotnet workload restore` at the root of your project?

This will force dotnet to install the required Maui dependencies. It should work correctly after that.

If still not, the Windows part of Fabulous might be too old and we need to update it.

**Comment by ners** [comment]
Thank you for the prompt response, it was indeed solved by `dotnet restore`. :slightly_smiling_face:
